money/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^money/settings/$', views.money_settings, name='money_settings'),

    url(r'^money/category/add/$', views.category_add, name="category_add"),
    url(r'^money/category/remove/(?P<slug>[\w-]+)/$', views.category_remove, name="category_remove"),
    url(r'^money/category/edit/(?P<slug>[\w-]+)/$', views.category_edit, name="category_edit"),


    url(r'^money/subcategory/add/$', views.subcategory_add, name="subcategory_add"),
    url(r'^money/subcategory/remove/(?P<pk>\d+)-(?P<slug>[\w-]+)/$', views.subcategory_remove, name="subcategory_remove"),
    url(r'^money/subcategory/edit/(?P<pk>\d+)-(?P<slug>[\w-]+)/$', views.subcategory_edit, name="subcategory_edit"),

    url(r'^money/list/$', views.money_list, name='money_list'),
    url(r'^money/list/add/$', views.money_list_item_add, name="money_list_item_add"),
    url(r'^money/list/remove/(?P<pk>\d+)/$', views.money_list_item_remove, name="money_list_item_remove"),
    url(r'^money/list/edit/(?P<pk>\d+)/$', views.money_list_item_edit, name="money_list_item_edit"),
    url(r'^money/analyze-monthly/$', views.money_analyze_monthly, name="money_analyze_monthly"),

    url(r'^money/export/xls/$', views.money_export_xls, name="money_export_xls"),

    url(r'^ajax/load_category/$', views.load_category, name='ajax_load_category'),
    url(r'^ajax/load_subcategory/$', views.load_subcategory, name='ajax_load_subcategory'),
    url(r'^ajax/add_category/$', views.category_add_modal, name="category_add_modal"),

    url(r'^api/data/spend-chart/$', views.SpendChartData.as_view(), name='api_spend_chart_data'),
    url(r'^api/data/category-chart/$', views.CategoryChartData.as_view(), name='api_category_chart_data'),
]

myproject/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('meters.urls')),
    url(r'', include('reminder.urls')),
    url(r'', include('money.urls')),
]

money/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
import datetime


class SpendType(models.Model):
    spend_type = models.CharField(max_length=50)
    spend_type_slug = models.SlugField(blank=True,
                                       null=True)
    created_by = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.spend_type

    def save(self, *args, **kwargs):
        self.spend_type_slug = slugify(self.spend_type)
        super(SpendType, self).save(*args, **kwargs)


class SpendCategory(models.Model):
    category_name = models.CharField(max_length=50)
    category_slug = models.SlugField(blank=True,
                                     null=True)
    spend_type = models.ForeignKey(SpendType, on_delete=models.CASCADE)
    created_by = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.category_name

    def save(self, *args, **kwargs):
        self.category_slug = slugify(self.category_name)
        super(SpendCategory, self).save(*args, **kwargs)


class SpendSubcategory(models.Model):
    subcategory_name = models.CharField(max_length=50)
    subcategory_slug = models.SlugField(blank=True,
                                        null=True)
    category = models.ForeignKey(SpendCategory, on_delete=models.CASCADE)
    created_by = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.subcategory_name

    def save(self, *args, **kwargs):
        self.subcategory_slug = slugify(self.subcategory_name)
        super(SpendSubcategory, self).save(*args, **kwargs)


class SpendItem(models.Model):
    spend_type = models.ForeignKey(SpendType, on_delete=models.CASCADE)
    category = models.ForeignKey(SpendCategory, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SpendSubcategory, on_delete=models.CASCADE)
    item_date = models.DateField(default=timezone.now)
    item_place = models.CharField(max_length=255)
    spender = models.CharField(max_length=50)
    comment = models.CharField(max_length=255, blank=True, default='')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=5, default="zł")
    created_by = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.item_date) + " - " + str(self.amount) + " " + self.currency + " (" + self.item_place + ")"

money/forms.py
from django import forms

from .models import SpendCategory, SpendSubcategory, SpendType, SpendItem


class SpendCategoryForm(forms.ModelForm):

    class Meta:
        model = SpendCategory
        fields = ('spend_type', 'category_name')


class SpendSubcategoryForm(forms.ModelForm):
    spend_type = forms.ModelChoiceField(queryset=SpendType.objects.all(),
                                        required=True)

    class Meta:
        model = SpendSubcategory
        fields = ('spend_type', 'category', 'subcategory_name')

    def __init__(self, *args, **kwargs):
        super(SpendSubcategoryForm, self).__init__(*args, **kwargs)
        #self.fields['category'].queryset = SpendCategory.objects.none()


class SpendItemForm(forms.ModelForm):

    class Meta:
        model = SpendItem
        fields = ('spend_type', 'category', 'subcategory', 'item_date',
                  'item_place', 'spender', 'amount', 'currency', 'comment')

money/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.db.models import Sum
from .models import SpendType, SpendCategory, SpendSubcategory, SpendItem
from .forms import SpendCategoryForm, SpendSubcategoryForm, SpendItemForm
from .filters import SpendItemFilter

from rest_framework.views import APIView
from rest_framework.response import Response

import xlwt, random


def money_settings(request):
    subcategory = SpendSubcategory.objects.all().order_by("category__category_name")
    category = SpendCategory.objects.all().order_by("category_name")

    return render(request, 'settings.html', {'subcategory': subcategory, 'category': category})


def category_edit(request, slug):
    category = get_object_or_404(SpendCategory, category_slug=slug)
    if request.method == "POST":
        form = SpendCategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            category.created_date = timezone.now()
            category.save()
            return redirect('money_settings')
    else:
        form = SpendCategoryForm(instance=category)
    return render(request, 'category_edit.html', {'form': form})


def category_add(request):
    if request.method == "POST":
        form = SpendCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            category.created_date = timezone.now()
            category.save()
            return redirect('money_settings')
    else:
        form = SpendCategoryForm()
    return render(request, 'category_edit.html', {'form': form})


def category_remove(request, slug):
    category = get_object_or_404(SpendCategory, category_slug=slug)
    if request.method == "POST":
        category.delete()
        return redirect('money_settings')
    return render(request, 'category_remove.html', {'category': category})


def subcategory_edit(request, slug, pk):
    subcategory = get_object_or_404(SpendSubcategory, subcategory_slug=slug, pk=pk)
    if request.method == "POST":
        form = SpendSubcategoryForm(request.POST, instance=subcategory)
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            category.created_date = timezone.now()
            category.save()
            return redirect('money_settings')
    else:
        form = SpendSubcategoryForm(instance=subcategory)
    return render(request, 'subcategory_edit.html', {'form': form})


def subcategory_add(request):
    if request.method == "POST":
        form = SpendSubcategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            category.created_date = timezone.now()
            category.save()
            return redirect('money_settings')
    else:
        form = SpendSubcategoryForm()
    return render(request, 'subcategory_edit.html', {'form': form})


def subcategory_remove(request, slug, pk):
    subcategory = get_object_or_404(SpendSubcategory, subcategory_slug=slug, pk=pk)
    if request.method == "POST":
        subcategory.delete()
        return redirect('money_settings')
    return render(request, 'subcategory_remove.html', {'subcategory': subcategory})


def load_category(request):
    spend_type_id = request.GET.get('spend_type')
    category = SpendCategory.objects.filter(spend_type=spend_type_id)
    return render(request, 'category_dropdown_list.html', {'category': category})


def load_subcategory(request):
    category_id = request.GET.get('category')
    subcategory = SpendSubcategory.objects.filter(category=category_id)
    return render(request, 'subcategory_dropdown_list.html', {'subcategory': subcategory})


def category_add_modal(request):
    if request.method == "POST":
        form = SpendCategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.created_by = request.user
            category.created_date = timezone.now()
            category.save()
            return redirect('money_settings')
    else:
        form = SpendCategoryForm()
    return render(request, 'category_edit_modal.html', {'form': form})


def money_list(request):
    spend_item_list_datalist = SpendItem.objects.order_by('item_place').values_list('item_place', flat=True).distinct()
    spend_spender_datalist = SpendItem.objects.order_by('spender').values_list('spender', flat=True).distinct()
    spend_year_datalist = SpendItem.objects.dates('item_date', 'year')
    spend_item_list = SpendItem.objects.all().order_by("-item_date")
    spend_item_filter = SpendItemFilter(request.GET, queryset=spend_item_list)
    return render(request, 'money_list.html', {'filter': spend_item_filter,
                                               'item_datalist': spend_item_list_datalist,
                                               'spender_datalist': spend_spender_datalist,
                                               'year_datalist': spend_year_datalist})


def money_list_item_add(request):
    spend_item_list_datalist = SpendItem.objects.order_by('item_place').values_list('item_place', flat=True).distinct()
    spend_spender_datalist = SpendItem.objects.order_by('spender').values_list('spender', flat=True).distinct()
    if request.method == "POST":
        form = SpendItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.created_date = timezone.now()
            item.save()
            return redirect('money_list')
    else:
        form = SpendItemForm()
    return render(request, 'money_list_item_edit.html', {'form': form,
                                                         'item_datalist': spend_item_list_datalist,
                                                         'spender_datalist': spend_spender_datalist})


def money_list_item_edit(request, pk):
    spend_item_list_datalist = SpendItem.objects.order_by('item_place').values_list('item_place', flat=True).distinct()
    spend_spender_datalist = SpendItem.objects.order_by('spender').values_list('spender', flat=True).distinct()
    money_item = get_object_or_404(SpendItem, pk=pk)
    if request.method == "POST":
        form = SpendItemForm(request.POST, instance=money_item)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.created_date = timezone.now()
            item.save()
            return redirect('money_list')
    else:
        form = SpendItemForm(instance=money_item)
    return render(request, 'money_list_item_edit.html', {'form': form,
                                                         'item_datalist': spend_item_list_datalist,
                                                         'spender_datalist': spend_spender_datalist})


def money_list_item_remove(request, pk):
    money_item = get_object_or_404(SpendItem, pk=pk)
    if request.method == "POST":
        money_item.delete()
        return redirect('money_list')
    return render(request, 'money_list_item_remove.html', {'money_item': money_item})


def money_export_xls(request):
    spend_item_list = SpendItem.objects.all()

    spend_type = request.GET.get('spend_type')
    if spend_type:
        spend_item_list = spend_item_list.filter(spend_type=spend_type)

    category = request.GET.get('category')
    if category:
        spend_item_list = spend_item_list.filter(category=category)

    subcategory = request.GET.get('subcategory')
    if subcategory:
        spend_item_list = spend_item_list.filter(subcategory=subcategory)

    item_place = request.GET.get('item_place')
    if item_place:
        spend_item_list = spend_item_list.filter(item_place=item_place)

    item_year = request.GET.get('item_year')
    if item_year:
        spend_item_list = spend_item_list.filter(item_date__year=item_year)

    min_date = request.GET.get('min_date')
    if min_date:
        spend_item_list = spend_item_list.filter(item_date__gt=min_date)

    max_date = request.GET.get('max_date')
    if max_date:
        spend_item_list = spend_item_list.filter(item_date__lt=max_date)

    spender = request.GET.get('spender')
    if spender:
        spend_item_list = spend_item_list.filter(spender=spender)

    spend_item_list = spend_item_list.order_by("-item_date")

    response = HttpResponse(content_type='text/ms-excel')
    filename = "money-data"
    response['Content-Disposition'] = 'attachment; filename={0}.xls'.format(filename)

    wb = xlwt.Workbook(encoding='utf-8')
    ws = wb.add_sheet("Consumptions")

    row_num = 0

    font_style = xlwt.XFStyle()
    font_style.font.bold = True

    date_format = xlwt.XFStyle()
    date_format.num_format_str = 'dd-mm-yyyy'

    columns = ['Data', 'Miejsce', 'Kwota', 'Waluta', 'Kto', 'Typ', 'Kategoria', 'Podkategoria', 'Komentarz']
    for col_num in range(len(columns)):
        ws.write(row_num, col_num, columns[col_num], font_style)

    font_style = xlwt.XFStyle()

    for i in spend_item_list:
        row_num += 1
        row = [i.item_date, i.item_place, i.amount, i.currency, i.spender, i.spend_type.spend_type,
               i.category.category_name, i.subcategory.subcategory_name, i.comment]
        for col_num in range(len(row)):
            if col_num == 0:
                ws.write(row_num, col_num, row[col_num], date_format)
            else:
                ws.write(row_num, col_num, row[col_num], font_style)

    wb.save(response)
    return response


def money_analyze_monthly(request):
    spend_amount = SpendType.objects.annotate(total_amount=Sum('spenditem__amount'))

money/templates/category_dropdown_list.html
<option value="">---------</option>
{% for cat in category %}
    <option value="{{ cat.pk }}">{{ cat.category_name }}</option>
{% endfor %}

money/templates/category_edit.html
{% extends 'base.html' %}

{% block title %}Liczniki{% endblock %}

{% block content %}
    <h1>Kategoria - edycja</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

money/templates/category_edit_modal.html
{% extends 'modal.html' %}

{% block id %}category_modal{% endblock %}

{% block title %}Kategoria - edycja{% endblock %}

{% block content %}
    <form id="category_modal_form" method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock %}

{% block form_id %}category_modal_form{% endblock %}

money/templates/money_list.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Zestawienie{% endblock %}

{% block content %}
    <div class="shadow-sm p-3 mb-1 bg-white rounded d-flex justify-content-between align-items-center">
        <h2>Wszystkie wydatki</h2>
        <div>
            <div class="btn-group dropleft">
                <button type="button" class="btn btn btn-outline-success btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-file-export"></i>
                    Eksportuj
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">PDF</a>
                    <a class="dropdown-item" href="{% url 'money_export_xls' %}?spend_type={{ filter.form.spend_type.value }}&category={{ filter.form.category.value }}&subcategory={{ filter.form.subcategory.value }}&item_place={{ filter.form.item_place.value }}&item_year={{ filter.form.item_year.value }}&min_date={{ filter.form.min_date.value }}&max_date={{ filter.form.max_date.value }}&spender={{ filter.form.spender.value }}" target="_blank" type="submit">Excel</a>
                    <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">CSV</a>
                </div>
            </div>
            <a href="{% url 'money_list_item_add' %}" class="btn btn-outline-success btn-sm" role="button" aria-pressed="true">
                <i class="fas fa-plus"></i>
                Dodaj
            </a>

        </div>
    </div>

    <div class="shadow-sm p-3 mb-1 bg-white rounded">
        <form method="get" id="SearchForm" data-category-url="{% url 'ajax_load_category' %}" data-subcategory-url="{% url 'ajax_load_subcategory' %}">
            <div class="toggler">
                <a data-toggle="collapse" href="#filter_panel" role="button" aria-expanded="true" aria-controls="filter_panel" class="collapsed">
                    <i class="fas fa-toggle-on fa-2x"></i>
                </a>
                <h4 style="margin-top: 0">Filtry</h4>
            </div>
            <div class="collapse" id="filter_panel">
                <div class="row">
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.spend_type.id_for_label }}">Typ:</label>
                        {% render_field filter.form.spend_type class="form-control form-control-sm" %}
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.category.id_for_label }}">Kategoria:</label>
                        {% render_field filter.form.category class="form-control form-control-sm" %}
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.subcategory.id_for_label }}">Podkategoria:</label>
                        {% render_field filter.form.subcategory class="form-control form-control-sm" %}
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.item_place.id_for_label }}">Miejsce (zawiera):</label>
                        {% render_field filter.form.item_place class="form-control form-control-sm" list="item_place_list" %}
                        <datalist id="item_place_list">
                            {% for item in item_datalist %}
                                <option value="{{ item }}">
                            {% endfor %}
                        </datalist>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.item_year.id_for_label }}">Rok:</label>
                        {% render_field filter.form.item_year class="form-control form-control-sm" list="year_list" %}
                        <datalist id="year_list">
                            {% for item in year_datalist %}
                                <option value="{{ item.year }}">
                            {% endfor %}
                        </datalist>
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.min_date.id_for_label }}">Data od:</label>
                        <input type="date" name="{{ filter.form.min_date.name }}" class="form-control form-control-sm" id="{{ filter.form.min_date.id_for_label }}">
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.max_date.id_for_label }}">Data do:</label>
                        <input type="date" name="{{ filter.form.max_date.name }}" class="form-control form-control-sm" id="{{ filter.form.max_date.id_for_label }}">
                    </div>
                    <div class="form-group col-sm-3">
                        <label for="{{ filter.form.spender.id_for_label }}">Osoba:</label>
                        {% render_field filter.form.spender class="form-control form-control-sm" list="spender_list" %}
                        <datalist id="spender_list">
                            {% for item in spender_datalist %}
                                <option value="{{ item }}">
                            {% endfor %}
                        </datalist>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="fas fa-filter"></i> Filtruj
                </button>
                <a class="btn btn-success btn-sm" href="{% url 'money_list' %}" role="button">
                    <i class="fas fa-sync-alt"></i> Wyczyść
                </a>
            </div>
        </form>
    </div>


    <div aria-label="breadcrumb"> {{ filter.form.instance.some_field }}
         <ol class="breadcrumb">
            {% if filter.form.spend_type.value %}
            <li class="breadcrumb-item active"><strong>Typ:</strong> {{ filter.form.spend_type.data }}</li>
            {% endif %}
            {% if filter.form.category.value %}
            <li class="breadcrumb-item active"><strong>Kategoria:</strong> {{ filter.form.category.value }}</li>
            {% endif %}
            {% if filter.form.subcategory.value %}
            <li class="breadcrumb-item active"><strong>Podkategoria:</strong> {{ filter.form.subcategory.value }}</li>
            {% endif %}
            {% if filter.form.item_place.value %}
            <li class="breadcrumb-item active"><strong>Miejsce:</strong> {{ filter.form.item_place.value }}</li>
            {% endif %}
            {% if filter.form.item_year.value %}
            <li class="breadcrumb-item active"><strong>Rok:</strong> {{ filter.form.item_year.value }}</li>
            {% endif %}
            {% if filter.form.min_date.value %}
            <li class="breadcrumb-item active"><strong>Data od:</strong> {{ filter.form.min_date.value }}</li>
            {% endif %}
            {% if filter.form.max_date.value %}
            <li class="breadcrumb-item active"><strong>Data do:</strong> {{ filter.form.max_date.value }}</li>
            {% endif %}
            {% if filter.form.spender.value %}
                <li class="breadcrumb-item active">spender={{ filter.form.spender.value }}</li>
            {% endif %}
        </ol>
    </div>


    <div class="p-3 mb-1">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Miejsce</th>
                    <th scope="col">Kwota</th>
                    <th scope="col">Kto</th>
                    <th scope="col">Typ</th>
                    <th scope="col">Kategoria</th>
                    <th scope="col">Subcategoria</th>
                    <th scope="col">Komentarz</th>
                    <th scope="col">Ustawienia</th>
                </tr>
            </thead>
            <tbody>
            {% for item in filter.qs %}
                <tr>
                    <td>{{ item.item_date }}</td>
                    <td>{{ item.item_place }}</td>
                    <td>{{ item.amount }} {{ item.currency }}</td>
                    <td>{{ item.spender }}</td>
                    <td>{{ item.spend_type.spend_type }}</td>
                    <td>{{ item.category.category_name }}</td>
                    <td>{{ item.subcategory.subcategory_name }}</td>
                    <td>{{ item.comment }}</td>
                    <td>
                        <a href="{% url 'money_list_item_edit' pk=item.pk %}" class="link">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a href="{% url 'money_list_item_remove' pk=item.pk %}" class="link">
                            <i class="far fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="9">No data</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $("#id_spend_type").change(function () {
          var url = $("#SearchForm").attr("data-category-url");
          var SpendTypeId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'spend_type': SpendTypeId
            },
            success: function (data) {
              $("#id_category").html(data);
            }
          });

        });

        $("#id_category").change(function () {
          var url = $("#SearchForm").attr("data-subcategory-url");
          var CategoryId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'category': CategoryId
            },
            success: function (data) {
              $("#id_subcategory").html(data);
            }
          });

        });
    </script>
{% endblock %}

money/templates/money_list_item_edit.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Rozliczenie{% endblock %}

{% block content %}
    <h1>Rozliczenie - dodaj/edytuj</h1>
    <form method="POST" class="post-form" id="AddMoneyItemForm" data-category-url="{% url 'ajax_load_category' %}" data-subcategory-url="{% url 'ajax_load_subcategory' %}">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="{{ form.spend_type.id_for_label }}">Typ:</label>
                {% render_field form.spend_type class="form-control form-control-sm" %}
            </div>
            <div class="form-group col-md-4">
                <label for="{{ form.category.id_for_label }}">Kategoria:</label>
                {% render_field form.category class="form-control form-control-sm" %}
            </div>
            <div class="form-group col-md-4">
                <label for="{{ form.subcategory.id_for_label }}">Podkategoria:</label>
                {% render_field form.subcategory class="form-control form-control-sm" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="{{ form.item_date.id_for_label }}">Data:</label>
                {% render_field form.item_date class="form-control form-control-sm" %}
            </div>
            <div class="form-group col-md-3">
                <label for="{{ form.item_place.id_for_label }}">Miejsce:</label>
                {% render_field form.item_place class="form-control form-control-sm" list="item_place_list" %}
                <datalist id="item_place_list">
                    {% for item in item_datalist %}
                        <option value="{{ item }}">
                    {% endfor %}
                </datalist>
            </div>
            <div class="form-group col-md-3">
                <label for="{{ form.spender.id_for_label }}">Osoba:</label>
                {% render_field form.spender class="form-control form-control-sm" list="spender_list" %}
                <datalist id="spender_list">
                    {% for item in spender_datalist %}
                        <option value="{{ item }}">
                    {% endfor %}
                </datalist>
            </div>
            <div class="form-group col-md-2">
                <label for="{{ form.amount.id_for_label }}">Kwota:</label>
                {% render_field form.amount class="form-control form-control-sm" %}
            </div>
            <div class="form-group col-md-1">
                <label for="{{ form.currency.id_for_label }}">Waluta:</label>
                {% render_field form.currency class="form-control form-control-sm" %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="{{ form.comment.id_for_label }}">Komentarz:</label>
                {% render_field form.comment class="form-control form-control-sm" %}
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-sm">
            <i class="fas fa-save"></i> Zapisz
        </button>
        <a class="btn btn-danger btn-sm" href="{% url 'money_list' %}" role="button">
            <i class="fas fa-times"></i> Anuluj
        </a>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        $("#id_spend_type").change(function () {
          var url = $("#AddMoneyItemForm").attr("data-category-url");
          var SpendTypeId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'spend_type': SpendTypeId
            },
            success: function (data) {
              $("#id_category").html(data);
            }
          });

        });

        $("#id_category").change(function () {
          var url = $("#AddMoneyItemForm").attr("data-subcategory-url");
          var CategoryId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'category': CategoryId
            },
            success: function (data) {
              $("#id_subcategory").html(data);
            }
          });

        });
    </script>
{% endblock %}

money/templates/subcategory_edit.html
{% extends 'base.html' %}

{% block title %}Liczniki{% endblock %}

{% block content %}
    <h1>Subkategoria - edycja</h1>
    <form method="POST" class="post-form" id="SubcategoryForm" data-category-url="{% url 'ajax_load_category' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

{% block scripts %}
    <script>
        $("#id_spend_type").change(function () {
          var url = $("#SubcategoryForm").attr("data-category-url");
          var SpendTypeId = $(this).val();

          $.ajax({
            url: url,
            data: {
              'spend_type': SpendTypeId
            },
            success: function (data) {
              $("#id_category").html(data);
            }
          });

        });
    </script>
{% endblock %}